#!/bin/sh

# Generate a unique petname for this machine instance
if [ -s ~/.petname ]
then
    echo "petname already set to \"$(cat ~/.petname)\""
    exit 0
fi

CODESPACES_DISPLAY_NAME=$(gh api /user/codespaces/$CODESPACE_NAME | jq -r .display_name)
if [ "$CODESPACES_DISPLAY_NAME" ]
then
    echo "Using Codespaces display name \"$CODESPACES_DISPLAY_NAME\" as petname"
    echo $CODESPACES_DISPLAY_NAME > ~/.petname
    exit 0
fi

# If go is installed, install golang-petname utility to GOBIN
if ! command -v go
then
    echo "go not installed, skipping petname generation"
    echo "no-petname" > ~/.petname
    exit 0
fi

echo "installing golang-petname"
go install github.com/dustinkirkland/golang-petname/cmd/petname@latest

# go env GOBIN may return an empty string
# https://github.com/golang/go/issues/23439#issuecomment-582483567
if [ -z $GOBIN ]
then
    GOBIN="$(go env GOPATH)/bin"
fi
echo "GOBIN: $GOBIN"

$GOBIN/petname > ~/.petname
echo "Generated petname: $(cat ~/.petname)"
